<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.rayzs.prof3brand</groupId>
    <artifactId>ProF3Brand</artifactId>
    <version>1.0.1</version>
    <packaging>pom</packaging>

    <modules>
        <module>bukkit</module>
        <module>bungee</module>
        <module>velocity</module>
        <module>api</module>
        <module>common</module>
    </modules>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub rayzsyt Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/rayzsyt/prof3brand</url>
        </repository>
    </distributionManagement>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>

                            <artifactSet>
                                <includes>
                                    <include>de.rayzs.prof3brand:api</include>
                                    <include>de.rayzs.prof3brand:common</include>
                                </includes>
                            </artifactSet>

                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <finalName>${project.parent.artifactId}-${project.name}-${project.version}</finalName>

                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>