name: ProF3Brand

version: 1.0.0
version-api: 1.13
main: de.rayzs.prof3brand.bukkit.ProF3BrandPlugin

author: Rayzs_YT
description: Fully customize the F3 server brand to your personal liking.
folia-supported: true

softdepend: ["PlaceholderAPI", "LuckPerms"]

commands:
  prof3brand:
    aliases: ["probrand", "brand", "f3brand"]
    permission: prof3brand.use